"""user table

Revision ID: 0952e0ecb2e8
Revises: 81af9ab1ae0f
Create Date: 2023-09-04 20:27:52.266935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0952e0ecb2e8'
down_revision = '81af9ab1ae0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['mobile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('points')
        batch_op.drop_column('mobile')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
