"""models2

Revision ID: 368f55f7301d
Revises: 
Create Date: 2023-09-03 21:00:35.527721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '368f55f7301d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('category', postgresql.ENUM('GENERAL', 'SAFETY', 'ENVIRONMENT', name='reportcategoryenum'), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lang', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('authenticity_before', sa.Float(), nullable=True),
    sa.Column('authenticity_after', sa.Float(), nullable=True),
    sa.Column('points_given', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('user')
    # ### end Alembic commands ###
