"""change2

Revision ID: d2de8c8fa742
Revises: db4b830e7a1a
Create Date: 2023-09-04 22:59:01.183013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2de8c8fa742'
down_revision = 'db4b830e7a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_mobile_key', type_='unique')
        batch_op.drop_constraint('user_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_password_key', ['password'])
        batch_op.create_unique_constraint('user_mobile_key', ['mobile'])
        batch_op.create_unique_constraint('user_email_key', ['email'])

    # ### end Alembic commands ###
